Updated background scripts.

diff --git a/src/background/gimp-scripts/Make-OilPainting b/src/background/gimp-scripts/Make-OilPainting
--- a/src/background/gimp-scripts/Make-OilPainting
+++ b/src/background/gimp-scripts/Make-OilPainting
@@ -33,57 +33,41 @@ set -eu
 
 
 # Example:
-# Make-Mosaic Image1.jpeg Mosaic1.png 24 4 4 --type hexagons --surface rough
-# Make-Mosaic Image1.jpeg Mosaic2.png 32 4 2 --type octagons --surface smooth
+# Make-OilPainting Image1.jpeg Painting1.png
+# Make-OilPainting Image1.jpeg Painting2.png --masksize 5
 
 
 # ====== Handle arguments ===================================================
 usage () {
    local exitCode="$1"
-   echo >&2 "Usage: $0 input_filename output_filename tile_size tile_height tile_spacing [--type|-t squares|hexagons|octagons|triangles] [--surface|-s smooth|rough] [--neatness|-n neatness] [--lightdirection|-l direction] [-c|--colorvariation variation] [--verbose|-v] [--quiet|-q] [--help|-h]"
-   echo >&2 "Example: $0 Image.jpeg Mosaic.png 24 4 4 --type hexagons --surface rough"
+   echo >&2 "Usage: $0 input_filename output_filename [--masksize|-s masksize] [--mode|-m rgb|intensity] [--verbose|-v] [--quiet|-q] [--help|-h]"
+   echo >&2 "Example: $0 Image.jpeg Cloth.png --masksize 5"
    exit "${exitCode}"
 }
 
 GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
 # shellcheck disable=SC2068
-options="$(${GETOPT} -o t:s:n:l:c:vqh --long type:,surface:,neatness:,lightdirection:,colorvariation:,verbose,quiet,help -a -- "$@")"
+options="$(${GETOPT} -o s:m:vqh --long masksize:,mode:,verbose,quiet,help -a -- "$@")"
 eval set -- "${options}"
 
-TILE_NEATNESS=0.65
-TILE_TYPESTRING="hexagons"
-TILE_TYPE="6"
-TILE_SURFACE=0
-LIGHT_DIRECTION=135
-COLOR_VARIATION=0.2
+MASKSIZE=8
+MODE=1
 VERBOSE=0
 while [ $# -gt 0 ] ; do
    case "$1" in
-      -t | --type)
-         TILE_TYPESTRING="$2"
+      -s | --masksize)
+         MASKSIZE="$2"
          shift 2
          ;;
-      -s | --surface)
-         if [ "$2" == "smooth" ] ; then
-            TILE_SURFACE=0
-         elif [ "$2" == "rough" ] ; then
-            TILE_SURFACE=1
+      -m | --mode)
+         if [ "$2" == "rgb" ] ; then
+            MODE=0
+         elif [ "$2" == "intensity" ] ; then
+            MODE=1
          else
-            echo >&2 "Invalid tile surface: $2"
+            echo >&2 "ERROR: Invalid mode!"
             exit 1
          fi
-         shift 2
-         ;;
-      -n | --neatness)
-         TILE_NEATNESS="$2"
-         shift 2
-         ;;
-      -l | --lightdirection)
-         LIGHT_DIRECTION="$2"
-         shift 2
-         ;;
-      -c | --colorvariation)
-         COLOR_VARIATION="$2"
          shift 2
          ;;
       -v | --verbose)
@@ -107,53 +91,18 @@ while [ $# -gt 0 ] ; do
   esac
 done
 
-if [ $# -ne 5 ] ; then
+if [ $# -ne 2 ] ; then
    usage 1
 fi
 INPUT_FILENAME="$1"
 OUTPUT_FILENAME="$2"
-TILE_SIZE=$3
-TILE_HEIGHT=$4
-TILE_SPACING=$5
 
 if [ ! -f "${INPUT_FILENAME}" ] ; then
    echo >&2 "ERROR: Input file ${INPUT_FILENAME} does not exist!"
    exit 1
 fi
-if [[ ! "${TILE_SIZE}" =~ ^[0-9]+$ ]] ; then
-   echo >&2 "ERROR: Invalid tile size!"
-   exit 1
-fi
-if [[ ! "${TILE_HEIGHT}" =~ ^[0-9]+$ ]] ; then
-   echo >&2 "ERROR: Invalid tile height!"
-   exit 1
-fi
-if [[ ! "${TILE_SPACING}" =~ ^[0-9]+$ ]] ; then
-   echo >&2 "ERROR: Invalid tile spacing!"
-   exit 1
-fi
-if [ "${TILE_TYPESTRING}" = "squares" ] ; then
-   TILE_TYPE=0
-elif [ "${TILE_TYPESTRING}" = "hexagons" ] ; then
-   TILE_TYPE=1
-elif [ "${TILE_TYPESTRING}" = "octagons" ] ; then
-   TILE_TYPE=2
-elif [ "${TILE_TYPESTRING}" = "triangles" ] ; then
-   TILE_TYPE=3
-else
-   echo >&2 "Invalid tile type ${TILE_TYPESTRING}!"
-   exit 1
-fi
-if [[ ! "${TILE_NEATNESS}" =~ ^([0-9]+|[0-9]+\.[0-9]*)$ ]] ; then
-   echo >&2 "ERROR: Invalid tile neatness ${TILE_NEATNESS}!"
-   exit 1
-fi
-if [[ ! "${COLOR_VARIATION}" =~ ^([0-9]+|[0-9]+\.[0-9]*)$ ]] ; then
-   echo >&2 "ERROR: Invalid color variation ${COLOR_VARIATION}!"
-   exit 1
-fi
-if [[ ! "${LIGHT_DIRECTION}" =~ ^([0-9]+)$ ]] ; then
-   echo >&2 "ERROR: Invalid light direction ${LIGHT_DIRECTION}!"
+if [[ ! "${MASKSIZE}" =~ ^([0-9]+)$ ]] ; then
+   echo >&2 "ERROR: Invalid mask size ${MASKSIZE}!"
    exit 1
 fi
 
@@ -184,15 +133,8 @@ rm -f "${OUTPUT_FILENAME}"
    ; ------ Initialise and load image ---------------------------------------
    ((inputFileName    "${INPUT_FILENAME}")
     (outputFileName   "${OUTPUT_FILENAME}")
-    (tileType         ${TILE_TYPE})
-    (tileTypeString   "${TILE_TYPESTRING}")
-    (tileSize         ${TILE_SIZE})
-    (tileHeight       ${TILE_HEIGHT})
-    (tileSpacing      ${TILE_SPACING})
-    (tileNeatness     ${TILE_NEATNESS})
-    (tileSurface      ${TILE_SURFACE})
-    (lightDirection   ${LIGHT_DIRECTION})
-    (colorVariation   ${COLOR_VARIATION})
+    (maskSize         ${MASKSIZE})
+    (mode             ${MODE})
     (image            (car (gimp-file-load RUN-NONINTERACTIVE inputFileName inputFileName)))
     (imageType        (if (not (defined? 'gimp-image-get-active-layer))
                          ; New Gimp 3.0 API:
@@ -214,31 +156,21 @@ rm -f "${OUTPUT_FILENAME}"
       (gimp-image-convert-rgb image))
 
    ; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-   ; GEGL Mosaic options: https://gegl.org/operations/gegl-mosaic.html
+   ; GEGL Oilify options: https://gegl.org/operations/gegl-oilify.html
    ; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
    (cond( (not(defined? 'plug-in-mosaic))
       ; New Gimp 3.0 API:
-      (gimp-drawable-merge-new-filter layer "gegl:mosaic" 0 LAYER-MODE-REPLACE 1.0
-          "tile-size"       tileSize
-          "tile-height"     tileHeight
-          "tile-spacing"    tileSpacing
-          "tile-neatness"   tileNeatness
-          "antialiasing"    TRUE
-          "light-dir"       lightDirection
-          "color-variation" colorVariation
-          "tile-type"       tileTypeString
-          "tile-surface"    tileSurface
-          "seed"            0
+      (gimp-drawable-merge-new-filter layer "gegl:oilify" 0 LAYER-MODE-REPLACE 1.0
+          "mask-radius" (max 1 (/ maskSize 2))
+          "use-inten"   mode
       )
    )
    (else
       ; Old Gimp 2.x API:
-      (plug-in-mosaic RUN-NONINTERACTIVE image layer
-         tileSize tileHeight tileSpacing
-         tileNeatness TRUE lightDirection colorVariation TRUE TRUE
-         tileType tileSurface FALSE
-   )))
+      (display maskSize) (newline)
+      (plug-in-oilify RUN-NONINTERACTIVE image layer maskSize mode)
+   ))
 
    ; ------ Save result -----------------------------------------------------
    (if (defined? 'gimp-drawable-merge-new-filter)
